### ISSUE TITLE
Support multiple projects per channel

### ISSUE THREAD

**Issue by throughnothing** [bigpresh/Bot-BasicBot-Pluggable-Module-GitHub#2]
I'm interested in implementing this, I was just wondering if you had any thoughts/preferences on how this should be done so that it could potentially be merged in here.  Thanks.

**Comment by bigpresh** [comment]
I'll have to have more of a think on how it can work.  I suspect there will need to be a "primary" project per channel, to which an unqualified mention of e.g. "Issue 42" would refer; additional projects could be added to be monitored for new/changed issues, and, in future, push notifications.

I'd appreciate any thoughts you have on good ways to achieve it, too!

**Comment by throughnothing** [comment]
This was my thought exactly.  I'm working through some ideas in a branch of mine, and I'll let you know what I come up with.  Thanks.

**Comment by throughnothing** [comment]
Here's something very, very rough that does work for me.  I also updated GitHub::PullRequests to use the same set projects that everything else uses, and support private repos (a requirement for me).

Branch is here:
https://github.com/throughnothing/Bot-BasicBot-Pluggable-Module-GitHub/tree/multiple-projects

Relevant commit is here:
https://github.com/throughnothing/Bot-BasicBot-Pluggable-Module-GitHub/commit/cccfd806047cb4c37425e15e9a53da99d7e85cb1

Suggestions/comments welcome :)

**Comment by bigpresh** [comment]
Just skimmed over it and it looks good - will try to find time later on to review it in more detail.  I note that we'll need a way to remove projects from a channel - perhaps `!setgithubproject` should become `!addgithubproject` or similar, and a `!deletegithubproject` command added to remove a project from a channel.

Alternatively, perhaps `!setgithubproject` should become `!setgithubprojects`, and accept multiple projects, with the first being the primary, so it's trivial to just clobber the current project settings with more.

I'm starting to think that the ability to provide auth details should be removed from the `!setgithubproject` command, and moved to a separate command, e.g. `!setauthforproject`; I think for the most common case, one or more public repos, that would simplify `!setgithubproject`, and make supporting multiple projects in one command easier.

For those who need to access private projects, they'd add the project with `!setgithubproject`, then add the auth details with e.g. `!setauthforproject foo/bar user:token`.  (This would mean that, if a project was being added to multiple channels, the auth details would only need to be provided once.)

**Comment by throughnothing** [comment]
Thanks for the comments.  I agree completely about `!addgithubproject`, as well as `!setauthforproject`, and `!deletegithubproject`.  I was thinking those should be separated out.  I'll work on implementing `!setgithubprojects` in the way you described, and then add the others.

I did find some silly mistakes I was making in that commit, here's my updated one:

https://github.com/throughnothing/Bot-BasicBot-Pluggable-Module-GitHub/commit/c00634c6369155e35525489422cb239bae6f2dc8

**Comment by bigpresh** [comment]
Great stuff - thanks for your work so far, your contribution is valued!

**Comment by throughnothing** [comment]
Hmm, do you think `!deletegithubproject` should be required to specify a channel, or should it delete that project from every channel if no channel is specified?

**Comment by bigpresh** [comment]
I'd say `!deletegithubproject` should take a project and channel, and delete the project from the specified channel only - which is exactly how you implemented it :)

When it deletes a project, it should probably check if any other channels still have it added, and, if it was the last reference, also delete any stored auth info.

**Comment by bigpresh** [comment]
Closing this issue since you kindly implemented it in PR4 which is now merged :)
